### PR TITLE
add loop to do SSL_read as many times as required

### PR DESCRIPTION
**Pull request by polmr**

### CODE REVIEW

**Comment by deleisha** [comment]
Thanks @polmr, 
Was thinking of fixing SSL_read handling, lot of work to be done on evt-tls. 
Appreciate it. 

My thought was to find out how many bytes are there to read and read those at a single read and fire callback once.
Until we find that, let us incorporate your changes

**Comment by polmr** [comment]
Happy to contribute, thanks for your work @deleisha !

**Comment by brucejee** [comment]
This pull request not merged into mater branch? I also met this problem, and I found master's code not use do while now, there are no way to fire callback once for multiple SSL records.

**Comment by deleisha** [comment]
Committed already https://github.com/deleisha/evt-tls/commit/bc6d73d818ac1a7cf267503ef7eeaf596b856720 

Please upgrade

**Pull request merged**
